<?xml version="1.0"?>
<robot name="oscar" xmlns:xacro="http://www.ros.org/wiki/xacro">
  
  <!-- see oscar_defaults.urdf.xacro for parameters expected by this model -->
   
  <!-- Common macros -->
  <xacro:include filename="$(find common_robots)/urdf/inertias.urdf.xacro" />
  <xacro:include filename="$(find common_robots)/urdf/materials.urdf" />
  <xacro:include filename="$(find common_robots)/urdf/sensors.urdf.xacro" />

  <!-- Car Parts -->
  <xacro:include filename="$(find oscar_description)/urdf/wheels.urdf.xacro" />
  
  <!-- Body -->
  <link name="base_link"></link>

  <link name="base_link_footprint"></link>
  <joint name="base_link_footprint_joint" type="fixed">
    <origin xyz="0 0 ${-left_wheel_radius}" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="base_link_footprint" />
  </joint>

  
  <link name="chassis_link">
    <visual>
      <origin xyz="${chassis_dx} 0.00  0.00" rpy="0 0 0"/>
      <geometry><box size="${chassis_length} ${chassis_width} ${chassis_height}"/></geometry>
      <material name="transp_green"/>
    </visual>
    <!-- <collision> -->
    <!--   <origin xyz="${chassis_dx} 0.00  0.00" rpy="0 0 0"/> -->
    <!--   <geometry><box size="${chassis_length} ${chassis_width} ${chassis_height}"/></geometry> -->
    <!-- </collision> -->
    <xacro:inertial_cuboid_with_pose mass="${chassis_mass}" x_length="${chassis_length}" y_length="${chassis_width}" z_length="${chassis_height}">
      <origin xyz="${chassis_dx} 0.00  0.00" rpy="0 0 0"/>
    </xacro:inertial_cuboid_with_pose> 
  </link>

  <joint name="base_link_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="chassis_link" />
  </joint>

  <!-- Wheels -->
  <xacro:rear_wheel prefix="left" wheel_radius="${left_wheel_radius}" lr_reflect="1">
    <origin xyz="0 ${(wheel_track-wheel_width)/2} 0" rpy="0 0 0" />
  </xacro:rear_wheel>
  <xacro:rear_wheel prefix="right"  wheel_radius="${right_wheel_radius}" lr_reflect="-1">
    <origin xyz="0 ${-(wheel_track-wheel_width)/2} 0" rpy="0 0 0" />
  </xacro:rear_wheel>

  <xacro:front_wheel wheel_radius="${front_wheel_radius}">
    <origin xyz="${front_wheel_L} 0 0" rpy="0 0 0" />
  </xacro:front_wheel>

  <!-- IMU -->
  <link name="imu_link">
    <visual><geometry><sphere radius="0.0025"/></geometry></visual>
  </link>
  <joint name="imu_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="imu_link" />
  </joint>

  <!-- Infrared Marker -->
  <xacro:if value="${use_smocap_ir_marker}">
    <xacro:cs_smocap_ir_marker mesh="${smocap_ir_marker_mesh}">
      <origin xyz="0 0 0.06" rpy="0 0 0" />
    </xacro:cs_smocap_ir_marker>
  </xacro:if>
    
  <!-- Camera -->
  <!-- <xacro:if value="${use_eachine_camera}"> -->
  <!--   <xacro:property name="cam_look_down_deg" value="25." /> -->
  <!--   <xacro:cs_camera_eachine> -->
  <!--     <origin xyz="0.09 0 0.04" rpy="0 ${cam_look_down_deg/180*pi}} 0" /> -->
  <!--   </xacro:cs_camera_eachine> -->
  <!-- </xacro:if> -->
  <!-- Camera -->
  <xacro:include filename="$(find common_robots)/urdf/sensors.urdf.xacro" />
  <xacro:if value="${use_camera}">
    <xacro:cs_camera_eachine cam_name="${cam_name}" origin_ref_frame="base_link_footprint">
      <origin xyz="${cam_cl_to_ref_xyz}" rpy="${cam_cl_to_ref_rpy}" />
    </xacro:cs_camera_eachine>
  </xacro:if>
  <xacro:if value="${use_camera2}">
    <xacro:cs_camera_eachine cam_name="${cam2_name}" origin_ref_frame="base_link_footprint">
      <origin xyz="${cam2_cl_to_ref_xyz}" rpy="${cam2_cl_to_ref_rpy}" />
    </xacro:cs_camera_eachine>
  </xacro:if>
  
</robot>
