teleop_twist_joy:
  axis_linear:  1
  scale_linear: 0.5
  scale_linear_turbo: 1.0
  axis_angular: 2
  scale_angular: 0.7
  enable_button: 4
  enable_turbo_button: 5
joy_node:
  deadzone: 0.01
  autorepeat_rate: 20
